### ISSUE TITLE
How to get Buffer work in React Native?

### ISSUE THREAD

**Issue by tasharofi** [peterp/redux-http-basic-auth-example#1]
Hi Peter, 

Thanks for your great authentication code for RN. 
Just a question, when I try to encode my username and password to base64 using new Buffer, the application throws exception that "Buffer is not defined." 
How did you manage to get Buffer working in RN?

Thanks,

**Comment by peterp** [comment]
Hey @tasharofi, I some how missed this - but I'm guessing that you figured it out?
